### PR TITLE
Add alternative to fs.existsSync

### LINKED ISSUE #18: fs.existsSync is not a function
I'm using [level](https://github.com/Level/level) in an electron app, and electron is complaining about [L10](https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L10). 

It seems that this has been deprecated?

### PR DESCRIPTION
**Pull request by n-riesco**
Fixes #18

### CODE REVIEW

**Comment by shotlom** [comment]
:+1:

**Comment by juliangruber** [comment]
should work, but can probably be formatted more nicely

**Comment by emilycoco** [comment]
Any updates on merging this? I'd like to be able to use an updated version of node/fs with this package.

**Comment by Twistedst** [comment]
Please merge this. I am currently running into the issue that this fixes.

**Comment by Twistedst** [comment]
For anyone trying to use this `npm i --save-dev TooTallNate/node-bindings#pull/20/head`

**Comment by ninabreznik** [comment]
Same problem. Please merge, if possible :)Thanks for this awesome module 👍

**Comment by TooTallNate** [comment]
Merged, thanks!

**Pull request merged**
